# config.yaml
bedrock:
  client: "your_bedrock_client_endpoint"
  model_id: "your_bedrock_model_id"
  embedding_model_id: "your_bedrock_embedding_model_id"

database:
  host: "your_database_host"
  port: "your_database_port"
  user: "your_database_user"
  password: "your_database_password"
  name: "your_database_name"

application:
  log_level: "INFO"